<a href="https://colab.research.google.com/github/bijoy-420/Pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#create model class
import torch
import torch.nn as nn

class model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [5]:
#create dataset
features=torch.rand(10,5)
#create model
model=model(features.shape[1])

#forward pass
model(features)

tensor([[0.4198],
        [0.5030],
        [0.4120],
        [0.4775],
        [0.4047],
        [0.4694],
        [0.4504],
        [0.4141],
        [0.4637],
        [0.4119]], grad_fn=<SigmoidBackward0>)

In [7]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1487,  0.1765, -0.1158, -0.2303,  0.3209]], requires_grad=True)

#show model

In [8]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

using 2 layer

In [14]:
#create model class
import torch
import torch.nn as nn

class model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [15]:
feature=torch.rand(10,5)
model1=model1(feature.shape[1])
model1(feature)

tensor([[0.6513],
        [0.6410],
        [0.6163],
        [0.6142],
        [0.6255],
        [0.6353],
        [0.6305],
        [0.6221],
        [0.6314],
        [0.6563]], grad_fn=<SigmoidBackward0>)

Parameter containing:
tensor([[ 0.2471, -0.0145, -0.1094, -0.4170, -0.1103],
        [ 0.0434,  0.4101,  0.1481,  0.0844,  0.3559],
        [-0.2106, -0.1154, -0.2882, -0.0111,  0.2361]], requires_grad=True)

In [18]:
summary(model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

using sequential

In [21]:
#create model class
import torch
import torch.nn as nn

class model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(


    nn.Linear(num_features,3),
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [22]:
featuress=torch.rand(10,5)
model2=model2(featuress.shape[1])

model2(featuress)

tensor([[0.4024],
        [0.4495],
        [0.4849],
        [0.5008],
        [0.4519],
        [0.4979],
        [0.5048],
        [0.4656],
        [0.4652],
        [0.4547]], grad_fn=<SigmoidBackward0>)