In [ ]:
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
if torch.cuda.is_available():
  print('Gpu is available')
  print(f'Using Gpu:{torch.cuda.get_device_name(0)}')
else:
  print('Gpu is not available,using cpu')

Gpu is not available,using cpu


# creating a tensor

In [ ]:
#using empty
a=torch.empty(2,3)


In [ ]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones( 2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.2379, 0.7887, 0.3416],
        [0.6240, 0.8649, 0.6239]])

In [ ]:
#manual_seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
#manual_seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
#using tensor
torch.tensor([[12,21,32],[2,1,5],[4,5,6]])

tensor([[12, 21, 32],
        [ 2,  1,  5],
        [ 4,  5,  6]])

In [ ]:
#arrange
print('using arrange->',torch.arange(0,20,2))
#using linspace
print('using linspace->',torch.linspace(0,20,10))

#using eye
print('using eye->',torch.eye(5,5))

#using full
print('using full->',torch.full((2,3),5))

using arrange-> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
using linspace-> tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [ ]:
x.shape

torch.Size([3])

In [ ]:
torch.empty_like(x)

tensor([[154766,      5,      5],
        [     5,      5,      5]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.5504, 0.9424, 0.3835],
        [0.6327, 0.5669, 0.3390]], dtype=torch.float64)

# Tensor Data Types

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.1],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 5., 6.]])

In [ ]:
#addition
x+2
#substraction
x-2
#multiplication
x*2
#Division
x/2
#int division
(x*100)//3
#mod
x%3
#power
x**2


tensor([[ 1,  4,  9],
        [ 4, 25, 36]])

# Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.6150, 0.4967, 0.4521],
        [0.0575, 0.0687, 0.0501]])
tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])


In [ ]:
#addition
a+b
#substraction
a-b
#multiplication
a*b
#Division
a/b
#mod
a%b
#power
a**b

tensor([[0.9948, 0.9763, 0.9083],
        [0.8693, 0.9204, 0.1161]])

In [ ]:
c=torch.tensor([1,-2,-3,4])
c

tensor([ 1, -2, -3,  4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2,  3, -4])

In [ ]:
d=torch.tensor([1.9,2.5,3.3,4.4])
d

tensor([1.9000, 2.5000, 3.3000, 4.4000])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 3., 4.])

In [ ]:
##ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.5000, 3.0000, 3.0000])

# Reduction operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[3., 0., 9.],
        [3., 7., 9.]])

In [ ]:
#sum
torch.sum(e)
#colsum
torch.sum(e,dim=0)
#rowsum
torch.sum(e,dim=1)


tensor([12., 19.])

In [ ]:
#mean
torch.mean(e)
#colmean
torch.mean(e,dim=0)
#rowmean
torch.mean(e,dim=1)

tensor([4.0000, 6.3333])

In [ ]:
#median
torch.median(e)
#max and min
torch.max(e)
torch.min(e)
#standrad deviation
torch.std(e)
#product
torch.prod(e)
#variance
torch.var(e)
#argmax(return max value position)
torch.argmax(e)
#argmin(inverse argmax)
torch.argmin(e)


tensor(1)

# Matrix operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)


tensor([[8, 3, 1],
        [8, 2, 6]])
tensor([[1, 4],
        [9, 1],
        [8, 9]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[43, 44],
        [74, 88]])

In [ ]:
vector1=torch.tensor([1,2,3,])
vector2=torch.tensor([4,5,6])
#dot product
torch.dot(vector1,vector2)

tensor(32)

In [ ]:
#transpose
print(f)
torch.transpose(f,0,1)

tensor([[8, 3, 1],
        [8, 2, 6]])


tensor([[8, 8],
        [3, 2],
        [1, 6]])

In [ ]:
#determinant
r=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(r)

tensor(56.0000)

In [ ]:
#inverse
torch.inverse(r)

tensor([[-0.0714,  0.6071, -0.3571],
        [-0.1071, -0.3393,  0.4643],
        [ 0.2143, -0.3214,  0.0714]])

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[7, 5, 2],
        [0, 3, 0]])
tensor([[8, 1, 6],
        [8, 8, 4]])


In [ ]:
#greater than
i>j
#less than
i<j
#equal to
i==j
#not equal to
i!=j


tensor([[True, True, True],
        [True, True, True]])

# Special functions

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[4., 0., 3.],
        [5., 9., 5.]])

In [ ]:
#log
torch.log(k)
#exp
torch.exp(k)
#sqrt
torch.sqrt(k)
#sin
torch.sin(k)
#cos
torch.cos(k)
#sigmoid
torch.sigmoid(k)
#tanh
torch.tanh(k)
#softmax
torch.softmax(k,dim=1)
#relu(negative value convert to zero)
torch.relu(k)


tensor([[4., 0., 3.],
        [5., 9., 5.]])

# **Inplace Operations**

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.3156, 0.8468, 0.3651],
        [0.0916, 0.6161, 0.0561]])
tensor([[0.4970, 0.4385, 0.5048],
        [0.3810, 0.4269, 0.1977]])


In [ ]:
a+b

tensor([[0.6257, 0.5311, 0.5733],
        [0.1065, 0.0997, 0.7693]])

In [ ]:
#add m  and n with result with m
m.add_(n)

tensor([[1.3096, 1.7239, 1.3747],
        [0.8535, 1.4700, 0.4516]])

In [ ]:
m

tensor([[0.8126, 1.2854, 0.8699],
        [0.4725, 1.0431, 0.2539]])

# copying a tensor

In [ ]:
t=torch.rand(2,3)
t

tensor([[0.9799, 0.9500, 0.0135],
        [0.6213, 0.5674, 0.9417]])

In [ ]:
b=t
b

tensor([[0.9799, 0.9500, 0.0135],
        [0.6213, 0.5674, 0.9417]])

In [ ]:
t[0][0]=100
t

tensor([[1.0000e+02, 9.5000e-01, 1.3469e-02],
        [6.2128e-01, 5.6744e-01, 9.4173e-01]])

In [ ]:

b

tensor([[1.0000e+02, 9.5000e-01, 1.3469e-02],
        [6.2128e-01, 5.6744e-01, 9.4173e-01]])

In [ ]:
#id indicate memory position
print(id(t))
print(id(b))

138910202825616
138911164597584


In [ ]:
b=t.clone()

In [ ]:
b
#id indicate memory position
print(id(t))
print(id(b))

138910202825616
138911164597584


# Tensor Operation on GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device=torch.device('cuda')

In [ ]:
#creating a new tensor on gpu
torch.rand((2,3),device=device)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
#moving a new tensor on gpu
g=torch.rand((2,3))
g.to(device)

AssertionError: Torch not compiled with CUDA enabled

# Reshaping Tensor

In [ ]:
h=torch.ones(4,4)
h

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
h.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
h.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
o=torch.rand(2,3,4)
o

tensor([[[0.8099, 0.1272, 0.4860, 0.0231],
         [0.6404, 0.5023, 0.8459, 0.5840],
         [0.1057, 0.9714, 0.0698, 0.7400]],

        [[0.1518, 0.7698, 0.6248, 0.6339],
         [0.3810, 0.9563, 0.9874, 0.4483],
         [0.3407, 0.5777, 0.8219, 0.9652]]])

In [ ]:
#permute
o.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
#unsqueeze
d=torch.rand(226,226,3)
d.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
w=torch.rand(1,20)
w.squeeze(0).shape
w

tensor([[0.8210, 0.4643, 0.5734, 0.5893, 0.5794, 0.9388, 0.2013, 0.5220, 0.1964,
         0.6137, 0.8640, 0.2935, 0.6916, 0.1706, 0.5294, 0.3794, 0.1991, 0.8305,
         0.5191, 0.2934]])

# Numpy and Pytorch

In [ ]:
import numpy as np

# **Tensor to Numpy array**

In [ ]:
a=torch.tensor([1,23,4])
a

tensor([ 1, 23,  4])

In [ ]:
b=a.numpy()
b

array([ 1, 23,  4])

In [ ]:
type(b)

numpy.ndarray

# Numpy array to tensor

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])